CREATE TABLE approval (
    id INT AUTO_INCREMENT PRIMARY KEY,
    emp_id INT NOT NULL,
    approvalstatus VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (emp_id) REFERENCES employee(id) ON DELETE CASCADE
);
