CREATE TABLE payroll (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    employee_id INT NOT NULL,
    employeeNo VARCHAR(50),
    name VARCHAR(100),
    contactNo VARCHAR(20),
    email VARCHAR(100),
    empStatus VARCHAR(20),
    designation VARCHAR(100),
    departments VARCHAR(100),
    grade INT,
    increment INT,
    scale DECIMAL(10, 2),
    basic DECIMAL(10, 2),
    account_number VARCHAR(50),
    e_tin VARCHAR(50),

    chargeAllw DECIMAL(10, 2),
    telephoneAllwance DECIMAL(10, 2),
    AdditionalDesignation VARCHAR(100),

    dearnessAllw DECIMAL(10, 2),
    houseAllw DECIMAL(10, 2),
    medicalAllw DECIMAL(10, 2),
    educationAllw DECIMAL(10, 2),
    festivalAllw DECIMAL(10, 2),
    researchAllw DECIMAL(10, 2),
    newBdYrAllw DECIMAL(10, 2),
    recreationAllw DECIMAL(10, 2),
    otherAllw DECIMAL(10, 2),

    gpf DECIMAL(10, 2),
    gpfInstallment DECIMAL(10, 2),
    houseDed DECIMAL(10, 2),
    benevolentFund DECIMAL(10, 2),
    insurance DECIMAL(10, 2),
    electricity DECIMAL(10, 2),
    hrdExtra DECIMAL(10, 2),
    clubSubscription DECIMAL(10, 2),
    assoSubscription DECIMAL(10, 2),
    transportBill DECIMAL(10, 2),
    telephoneBill DECIMAL(10, 2),
    pensionFund DECIMAL(10, 2),
    fishBill DECIMAL(10, 2),
    incomeTax DECIMAL(10, 2),
    donation DECIMAL(10, 2),
    guestHouseRent DECIMAL(10, 2),
    houseLoanInstallment_1 DECIMAL(10, 2),
    houseLoanInstallment_2 DECIMAL(10, 2),
    houseLoanInstallment_3 DECIMAL(10, 2),
    salaryAdjustment DECIMAL(10, 2),
    revenue DECIMAL(10, 2),
    otherDed DECIMAL(10, 2),
    month INT,
    year INT,
    FOREIGN KEY (employee_id) REFERENCES employee(id) ON DELETE CASCADE
);
